### PR TITLE
so i added annotation logging to ftclib, what could possibly go wrong

### PR DESCRIPTION
**Pull request by 1198159**
it works, its tested irl and in sim in identical application

this adds a new feature, Annotation Logging

this does not add a breaking bug (well i hope it doesnt)

### CODE REVIEW

**Comment by 1198159** [comment]
[https://github.com/technototes/TechnoLog](url)

**Comment by puravdatta-sudo** [comment]
I think we would prefer to not add any outside library dependencies as a transitive dependency. If you would like to add it to the main library we could consider it.

**Comment by 1198159** [comment]
good point
logging is still in development, so ill wait
(im adding opmode black/whitelists so i can choose what opmode for the log to work in)

**Comment by puravdatta-sudo** [comment]
maybe close the pr for right now and make another one when it's done?

**Comment by 1198159** [comment]
yeah

**Pull request closed without merging**
