### PR TITLE
Introduce v1.1.0 to development branch

### PR DESCRIPTION
**Pull request by JIceberg**
# Introduce v1.1.0 to development branch

## What kind of change does this PR introduce?
This is the new version for FTCLib! v1.1.0 improves upon repository organization and unnecessary abstraction. There are also a few slight improvements in functionality of several features.

## Did this PR introduce a breaking change?
* Yes

The refactoring of the repository is likely the breaking change here. Everything had to be redone, modules were renamed, and several were deleted, in place for utilizing the official aars released by the tech team on bintray.

### CODE REVIEW

**Comment by JIceberg** [comment]
Are you kidding me? The only breaking change is the build.gradle file in the FtcLib module.

**Comment by JarnaChao09** [comment]
> Are you kidding me? The only breaking change is the build.gradle file in the FtcLib module.

its always gradle

**Comment by JIceberg** [comment]
We can delete the `build.gradle` file in FtcLib (and that folder itself) after we merge.

**Review by puravdatta-sudo — APPROVED** [review]
Looks good,ready for the DOCUMENTATION grind.

**Pull request merged**
