### PR TITLE
Change EOCV Version to 1.4.2

### PR DESCRIPTION
**Pull request by JIceberg**
# Change EOCV Version to 1.4.2

Please note that we accept pull requests from anyone, but that does not mean it will be merged.

## What kind of change does this PR introduce?
* Other - change version of EOCV to v1.4.2

I also changed the vision version from 1.1.0 to 1.2.0 for the next release.

## Did this PR introduce a breaking change?
Not for FTCLib - all changes can be found in the [EOCV changelog](https://github.com/OpenFTC/EasyOpenCV#v142).

__Please make sure your PR satisfies the requirements of [the contributing page](CONTRIBUTING.md)__

### CODE REVIEW

**Comment by JIceberg** [comment]
We should test the changes (i.e. the switch to native code for Camera2 and Webcam) before merge.

**Review by puravdatta-sudo — APPROVED** [review]
Gotta get this change out quick!

**Review by puravdatta-sudo — COMMENTED** [review]
But still need to update and review that everything works. Question: where are those cv unit tests at?

**Comment by JIceberg** [comment]
> But still need to update and review that everything works. Question: where are those cv unit tests at?

Well, the unit tests for windows are in #126. We need to work on those get them settled and maybe expand to other OS if needed.

**Review by JarnaChao09 — APPROVED** [review]

**Review by puravdatta-sudo — APPROVED** [review]
Looks good.

**Pull request merged**
