### PR TITLE
Add Constructor That Takes The SDK Object to Hardware Objects

### PR DESCRIPTION
**Pull request by JIceberg**
#157

### CODE REVIEW

**Review by JarnaChao09 — DISMISSED** [review]
looks good to me

**Review by Lunerwalker2 — APPROVED** [review]
Looks great

**Comment by JIceberg** [comment]
Sorry, the old approvals got removed because they were stale post-recent commit. Can y'all take a look once more?

**Review by JarnaChao09 — DISMISSED** [review]

**Review by Lunerwalker2 — COMMENTED** [review]
Are we going to have any way to use a DcMotorSimple (or just anything without an encoder)? I can see it possibly being used when you have a dead wheel encoder on the same port as the motor you are dealing with.

**Comment by JIceberg** [comment]
> Are we going to have any way to use a DcMotorSimple (or just anything without an encoder)? I can see it possibly being used when you have a dead wheel encoder on the same port as the motor you are dealing with.

I'm not sure what you mean, exactly. `DcMotorSimple` is essentially the same as `DcMotor` but with a few less features if I recall correctly. I'm not sure of how useful that would be to implement anywhere.

**Comment by JIceberg** [comment]
For dead wheels, the currently recommend way has two methods:
1. There is a motor in the port used for something else, like the front left drive wheel. This would be created as such:
```java
Motor frontLeft = new Motor(hardwareMap, "fL");

Motor.Encoder leftOdometer = frontLeft.encoder;
```
2. There is no motor plugged into that port, so we can just name it as the odometer in the config.
```java
Motor.Encoder = new Motor(hardwareMap, "left_odometer").encoder;
```

**Pull request closed without merging**
