### PR TITLE
AprilTag Feature Support

### LINKED ISSUE #226: Feature Request: Implement April Tag Reading Functionality
In all seasons, and in this season especially, April Tag detection would be helpful. 
I am willing to work on this feature.

### PR DESCRIPTION
**Pull request by Powercube7**
## What kind of change does this PR introduce?

* Feature: This PR has the scope of introducing EasyOpenCV's AprilTag support to FTCLib. Same idea as #228 except the PR has been updated more frequently. Closes #226 

## Did this PR introduce a breaking change?
* Unknown: The code has yet to be tested, however, no errors occurred during compiling.

### CODE REVIEW

**Review by JarnaChao09 — APPROVED** [review]

**Comment by Powercube7** [comment]
@JIceberg can you review my PR, please?

**Comment by JIceberg** [comment]
Quick question before review: do you have proof/verification of correctness (i.e., that these have been proven to work as expected)? And if so, could you attach some pipeline output images from dashboard/camera to this PR?

**Comment by Powercube7** [comment]
IMG20230125151443

Proof of correctness + Sample Usage

**Review by JIceberg — COMMENTED** [review]
LGTM

**Review by JIceberg — APPROVED** [review]

**Pull request merged**
